spring.application.name=semana7_depositos
# URL de la base de datos (cambia "nombre_tu_bd" por el tuyo)
spring.datasource.url=jdbc:mysql://localhost:3306/banco_pichincha?useSSL=false&serverTimezone=UTC
# Tu usuario de MySQL (normalmente es root)
spring.datasource.username=root
# Tu contraseña de MySQL
spring.datasource.password=

# Esto permite que Spring cree las tablas automáticamente basándose en tus clases @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect